#!/usr/bin/env bash
# script to transfer files from client to server

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
else
  if command -v "ssh" >/dev/null 2>&1; then
    echo "ssh is already installed."
  else
    sudo apt-get update
    sudo apt-get install -y openssh-client
  fi
  scp -i "$4" "$1" "$3@$2:~/"
fi
