#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting
sudo apt-get update
sudo apt-get install -y nginx
Str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=8CBjKLGwLqE permanent;"
sudo sed -i "s/server_name _;/$Str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
