#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting
sudo apt-get update
sudo apt-get install -y nginx
String="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com permanent;"
sudo sed -i "s/server_name _;/$String/" /etc/nginx/sites-enabled/default
sudo service nginx restart
