#!/usr/bin/env bash
#Install nginx web server and Redirection

c_header="add_header X-Served-By \$hostname"
sudo apt-get -y update
sudo apt-get -y install nginx
file=/var/www/html/index.html
file_re=/etc/nginx/sites-available/default
echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
	root /var/www/html;
	index index.html;
    }
}' | sudo tee $file_re
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "s/server_name _;/&\n\terror_page 404 \/custom_404.html;/" /etc/nginx/sites-enabled/default
sudo bash -c "echo 'Hello World!' > $file"
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\t$c_header;/" /etc/nginx/sites-available/default
sudo service nginx restart
