#!/usr/bin/env bash
# Update the system
sudo apt-get update
# sudo apt-get upgrade -y
# Install HAProxy
sudo apt-get install haproxy -y
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\
listen 376963-lb-01
  bind *:80
  mode http
  balance roundrobin
  option httpclose
  option forwardfor
  server 376963-web-02 52.91.121.75:80 check
  server 376963-web-01 54.164.103.65:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
