#!/usr/bin/env bash
# script that configures a server to listen on port 80

apt update
apt install nginx -y
sh -c 'echo "server {
  listen 80;
}" >> /etc/nginx/sites-available/default'
service nginx restart
