#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

IFS=":"
while read -r username password uid gid info homedir shell; do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done </etc/passwd
unset IFS
