#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0
min=1
while [[ $hour -lt 13 ]]; do
	echo "Hour: $hour"
	while [[ $min -lt 60 ]]; do
		echo $min
		((min++))
	done
	min=1
	((hour++))
done
